/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class ExploTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, ExploTimeoutError.prototype);
    }
}
