/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface DeleteCustomerRequest {
    /** This is the current Customer token you have for the Customer you want to delete */
    currentToken: string;
}
