/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface RefreshCustomerTokenRequest {
    /** This is the current customer token you have for the customer that you want to rotate. */
    currentToken: string;
}
