/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { ZachkirschApi } from "@fern-api/explo";
import * as core from "../../../../../core";

export const DeleteCustomerRequest: core.serialization.Schema<
    serializers.DeleteCustomerRequest.Raw,
    ZachkirschApi.DeleteCustomerRequest
> = core.serialization.object({
    currentToken: core.serialization.property("current_token", core.serialization.string()),
});

export declare namespace DeleteCustomerRequest {
    interface Raw {
        current_token: string;
    }
}
