/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { ZachkirschApi } from "@fern-api/explo";
import * as core from "../../../../core";

export const Customer: core.serialization.ObjectSchema<serializers.Customer.Raw, ZachkirschApi.Customer> =
    core.serialization.object({
        teamId: core.serialization.property("team_id", core.serialization.number()),
        token: core.serialization.string(),
        name: core.serialization.string(),
        providedId: core.serialization.property("provided_id", core.serialization.string()),
        isDemoGroup: core.serialization.property("is_demo_group", core.serialization.boolean()),
        properties: core.serialization.unknown(),
    });

export declare namespace Customer {
    interface Raw {
        team_id: number;
        token: string;
        name: string;
        provided_id: string;
        is_demo_group: boolean;
        properties?: unknown;
    }
}
