/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Explo } from "@fern-api/explo";
import * as core from "../../../../core";

export const GetOrCreateCustomerResponse: core.serialization.ObjectSchema<
    serializers.GetOrCreateCustomerResponse.Raw,
    Explo.GetOrCreateCustomerResponse
> = core.serialization
    .object({
        newCustomer: core.serialization.property("new_customer", core.serialization.boolean()),
        customer: core.serialization.lazyObject(async () => (await import("../../..")).Customer),
    })
    .extend(core.serialization.lazyObject(async () => (await import("../../..")).BaseResponse));

export declare namespace GetOrCreateCustomerResponse {
    interface Raw extends serializers.BaseResponse.Raw {
        new_customer: boolean;
        customer: serializers.Customer.Raw;
    }
}
