/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { ZachkirschApi } from "@fern-api/explo";
import * as core from "../../../../core";

export const RefreshCustomerTokenResponse: core.serialization.ObjectSchema<
    serializers.RefreshCustomerTokenResponse.Raw,
    ZachkirschApi.RefreshCustomerTokenResponse
> = core.serialization
    .object({
        customer: core.serialization.lazyObject(async () => (await import("../../..")).Customer),
    })
    .extend(core.serialization.lazyObject(async () => (await import("../../..")).BaseResponse));

export declare namespace RefreshCustomerTokenResponse {
    interface Raw extends serializers.BaseResponse.Raw {
        customer: serializers.Customer.Raw;
    }
}
