/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Explo } from "@fern-api/explo";
import * as core from "../../../../core";

export const UpdateCustomerResponse: core.serialization.ObjectSchema<
    serializers.UpdateCustomerResponse.Raw,
    Explo.UpdateCustomerResponse
> = core.serialization
    .object({
        customer: core.serialization.lazyObject(async () => (await import("../../..")).Customer),
    })
    .extend(core.serialization.lazyObject(async () => (await import("../../..")).BaseResponse));

export declare namespace UpdateCustomerResponse {
    interface Raw extends serializers.BaseResponse.Raw {
        customer: serializers.Customer.Raw;
    }
}
