/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { ZachkirschApi } from "@fern-api/explo";

export interface DeleteCustomerResponse extends ZachkirschApi.BaseResponse {}
