/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { ZachkirschApi } from "@fern-api/explo";

export interface RefreshCustomerTokenResponse extends ZachkirschApi.BaseResponse {
    /** The contents of the customer */
    customer: ZachkirschApi.Customer;
}
