/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Explo } from "@fern-api/explo";

export interface RefreshCustomerTokenResponse extends Explo.BaseResponse {
    /** The contents of the customer */
    customer: Explo.Customer;
}
