/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface BaseResponse {
    /** Indicates whether the call was successful. 1 if successful, 0 if not. */
    success: number;
}
