/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as core from "./core";
import { Customer } from "./api/resources/customer/client/Client";

export declare namespace ExploClient {
    interface Options {
        environment: string;
        token: core.Supplier<string>;
    }
}

export class ExploClient {
    constructor(private readonly options: ExploClient.Options) {}

    private _customer: Customer | undefined;

    public get customer(): Customer {
        return (this._customer ??= new Customer(this.options));
    }
}
